annotations:
  artifacthub.io/changes: "- \"fix(Traefik Proxy): :bug: abortOnPluginFailure not
    released yet\"\n- \"feat(deps): update traefik docker tag to v3.2.2\"\n- \"feat(Traefik
    Proxy): support NativeLB option in GatewayAPI provider\"\n- \"feat(Traefik Proxy):
    add `tracing`parameters to helm chart values\"\n- \"feat(Traefik Proxy): :art:
    harmonize semverCompare calls\"\n- \"feat(Gateway API): update sigs.k8s.io/gateway-api
    to v1.2.1\"\n- \"chore(release): \U0001F680 publish v33.2.0\"\n"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Traefik Proxy
  catalog.cattle.io/kube-version: '>=1.22.0-0'
  catalog.cattle.io/release-name: traefik
apiVersion: v2
appVersion: v3.2.2
description: A Traefik based Kubernetes ingress controller
home: https://traefik.io/
icon: file://assets/icons/traefik.png
keywords:
- traefik
- ingress
- networking
kubeVersion: '>=1.22.0-0'
maintainers:
- email: michel.loiseleur@traefik.io
  name: mloiseleur
- email: charlie.haley@traefik.io
  name: charlie-haley
- email: remi.buisson@traefik.io
  name: darkweaver87
- name: jnoordsij
name: traefik
sources:
- https://github.com/traefik/traefik
- https://github.com/traefik/traefik-helm-chart
type: application
version: 33.2.0
