annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: NGINX Ingress Controller
  catalog.cattle.io/kube-version: '>= 1.23.0-0'
  catalog.cattle.io/release-name: nginx-ingress
apiVersion: v2
appVersion: 4.0.0
description: NGINX Ingress Controller
home: https://github.com/nginxinc/kubernetes-ingress
icon: file://assets/icons/nginx-ingress.png
keywords:
- ingress
- nginx
kubeVersion: '>= 1.23.0-0'
maintainers:
- email: kubernetes@nginx.com
  name: nginxinc
name: nginx-ingress
sources:
- https://github.com/nginxinc/kubernetes-ingress/tree/v4.0.0/charts/nginx-ingress
type: application
version: 2.0.0
