annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Vals-Operator
  catalog.cattle.io/kube-version: '>= 1.19.0-0'
  catalog.cattle.io/release-name: vals-operator
apiVersion: v2
appVersion: v0.7.11
description: 'This helm chart installs the Digitalis Vals Operator to manage and sync
  secrets from supported backends into Kubernetes. ## About Vals-Operator Here at
  [Digitalis](https://digitalis.io) we love [vals](https://github.com/helmfile/vals),
  it''s a tool we use daily to keep secrets stored securely. Inspired by this tool,
  we have created an operator to manage Kubernetes secrets. *vals-operator* syncs
  secrets from any secrets store supported by [vals](https://github.com/helmfile/vals)
  into Kubernetes. Also, `vals-operator` supports database secrets as provider by
  [HashiCorp Vault Secret Engine](https://developer.hashicorp.com/vault/docs/secrets/databases). '
icon: file://assets/icons/vals-operator.png
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: info@digitalis.io
  name: Digitalis.IO
name: vals-operator
type: application
version: 0.7.11
