annotations:
  artifacthub.io/changes: |
    - Support PodMonitor as alternative to ServiceMonitor (#271)
    - Use correct values for PodMonitor test (#272)
    - Support to specify HPA behavior (#274)
    - Make controller.podAnnotations templatable (#276)
    - Fix controller.podAnnotations not being templatable in every location (#277)
    - Make controller.config templatable (#279)
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: HAProxy Kubernetes Ingress Controller
  catalog.cattle.io/kube-version: '>=1.23.0-0'
  catalog.cattle.io/release-name: kubernetes-ingress
apiVersion: v2
appVersion: 3.1.0-rc1
description: A Helm chart for HAProxy Kubernetes Ingress Controller
home: https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress
icon: file://assets/icons/haproxy.png
keywords:
- ingress
- haproxy
kubeVersion: '>=1.23.0-0'
maintainers:
- email: dkorunic@haproxy.com
  name: Dinko Korunic
name: haproxy
sources:
- https://github.com/haproxytech/kubernetes-ingress
type: application
version: 1.44.0
