annotations:
  artifacthub.io/changes: |
    - Add envFrom to Deployment and Deamonset (#256)
    - Remove pod annotations from deployment (#259)
    - Add possibility to set crdjob annotations (#264)
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: HAProxy Kubernetes Ingress Controller
  catalog.cattle.io/kube-version: '>=1.23.0-0'
  catalog.cattle.io/release-name: kubernetes-ingress
apiVersion: v2
appVersion: 3.0.4
description: A Helm chart for HAProxy Kubernetes Ingress Controller
home: https://github.com/haproxytech/helm-charts/tree/main/kubernetes-ingress
icon: file://assets/icons/haproxy.png
keywords:
- ingress
- haproxy
kubeVersion: '>=1.23.0-0'
maintainers:
- email: dkorunic@haproxy.com
  name: Dinko Korunic
name: haproxy
sources:
- https://github.com/haproxytech/kubernetes-ingress
type: application
version: 1.42.0
