annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: K10
  catalog.cattle.io/kube-version: '>= 1.17.0-0'
  catalog.cattle.io/release-name: k10
apiVersion: v2
appVersion: 7.0.13
dependencies:
- condition: grafana.enabled
  name: grafana
  repository: ""
  version: 8.5.8
- condition: prometheus.server.enabled
  name: prometheus
  repository: ""
  version: 25.28.0
description: Kasten’s K10 Data Management Platform
home: https://kasten.io/
icon: file://assets/icons/k10.png
kubeVersion: '>= 1.17.0-0'
maintainers:
- email: contact@kasten.io
  name: kastenIO
name: k10
version: 7.0.1301
