annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Added digests for images"
  artifacthub.io/containsSecurityUpdates: "false"
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Codefresh
  catalog.cattle.io/kube-version: '>=1.18-0'
  catalog.cattle.io/release-name: ""
apiVersion: v2
dependencies:
- name: cf-common
  repository: oci://quay.io/codefresh/charts
  version: 0.21.0
description: A Helm chart for Codefresh Runner
home: https://codefresh.io/
icon: file://assets/icons/cf-runtime.png
keywords:
- codefresh
- runner
kubeVersion: '>=1.18-0'
maintainers:
- name: codefresh
  url: https://codefresh-io.github.io/
name: cf-runtime
sources:
- https://github.com/codefresh-io/venona
version: 6.4.9
