annotations:
  artifacthub.io/links: |
    - name: Instana website
      url: https://www.ibm.com/products/instana
    - name: Instana Helm charts
      url: https://github.com/instana/helm-charts
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Instana Agent
  catalog.cattle.io/kube-version: '>=1.21-0'
  catalog.cattle.io/release-name: instana-agent
apiVersion: v2
appVersion: 1.285.0
description: Instana Agent for Kubernetes
home: https://www.instana.com/
icon: file://assets/icons/instana-agent.png
kubeVersion: '>=1.21-0'
maintainers:
- email: felix.marx@ibm.com
  name: FelixMarxIBM
- email: henning.treu@ibm.com
  name: htreu
- email: konrad.ohms@de.ibm.com
  name: Konrad-Ohms
name: instana-agent
sources:
- https://github.com/instana/instana-agent-docker
version: 2.0.0
