annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Percona Server for MongoDB
  catalog.cattle.io/kube-version: '>=1.21-0'
  catalog.cattle.io/release-name: psmdb-db
apiVersion: v2
appVersion: 1.17.0
description: A Helm chart for installing Percona Server MongoDB Cluster Databases
  using the PSMDB Operator.
home: https://www.percona.com/doc/kubernetes-operator-for-psmongodb/index.html
icon: file://assets/icons/psmdb-db.png
kubeVersion: '>=1.21-0'
maintainers:
- email: tomislav.plavcic@percona.com
  name: tplavcic
- email: natalia.marukovich@percona.com
  name: nmarukovich
name: psmdb-db
version: 1.17.1
