apiVersion: v2
appVersion: 2.37.0
description: Crate Operator CRDs - Helm chart for installing and upgrading Custom
  Resource Definitions (CRDs) for the Crate Operator.
maintainers:
- name: Crate.io
name: crate-operator-crds
type: application
version: 2.37.0
