name: Release Partner Charts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Update main-source branch
      run: |
        scripts/pull-ci-scripts
        bin/partner-charts-ci auto
        git push origin main-source

    - name: Create PR to update main branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        # checkout action only fetches main-source, so we need to fetch main branch also
        git fetch origin main --depth 1
        git checkout main
        UPDATE_BRANCH="auto-update/$(date '+%s')"
        git checkout -b "$UPDATE_BRANCH"
        git rm -r assets index.yaml
        git checkout main-source -- assets index.yaml
        git commit -m "Update partner charts"
        git push --set-upstream origin "$UPDATE_BRANCH"
        TITLE="Update partner charts"
        BODY="This PR was created by workflow \"$GITHUB_WORKFLOW\"."
        gh pr create --repo "$GITHUB_REPOSITORY" --base main --head "$UPDATE_BRANCH" --title "$TITLE" --body "$BODY"
